### ISSUE TITLE
Compatibility with Puppet 7

### ISSUE THREAD

**Issue by mosesdd** [voxpupuli/puppet-puppet_certificate#10]
Compatibility with Puppet 7 would be nice. I get following error with Puppet 7:

`Could not evaluate: uninitialized constant Puppet::SSL::Key`

**Comment by fraenki** [comment]
This change in one of the forks may be a starting point:
https://github.com/btolab/puppet-module-puppet_certificate/commit/8b30f8eb387e898b47b5090e136f17ab34e2b5dd

**Comment by fraenki** [comment]
Here's a summary of the removed code in Puppet 7:
https://tickets.puppetlabs.com/browse/PUP-10252

I don't know if there are any valid/compatible replacements available in Puppet 7. So maybe just add the required files to this module?

**Comment by huckabeec** [comment]
Before I try bumbling through the code, has anyone else made progress on refactoring this already for 7 ?

**Comment by alexjfisher** [comment]
I'm currently working on this, and _might_ have something working.

**Comment by alexjfisher** [comment]
@mosesdd @huckabeec Would you like to give https://github.com/reidmv/puppet-module-puppet_certificate/pull/11 a go?
