### ISSUE TITLE
New release to the forge

### ISSUE THREAD

**Issue by mcanevet** [voxpupuli/puppet-puppet_certificate#6]
@reidmv Would it be possible to release a new version to the forge? As os beaker4, dependencies are fetch from the `metadata.json` file and this file can only declare dependencies from the Forge.
It the mean time, we'll push to the forge our fork in the camptocamp namespace, that we'll remove as soon as you updated your version on the forge.

**Comment by alexjfisher** [comment]
`1.0.0` has been [released](https://forge.puppetlabs.com/modules/puppet/puppet_certificate/1.0.0/) in voxpupuli's `puppet` namespace.
